### ISSUE TITLE
Mavenized the project

### ISSUE THREAD

**Issue by kevzlou7979** [Legioth/Srp4Gwt#3]
Hi there,

This is awesome library for SRP on GWT, do you have any plans to mavenized this project?

Best Regards,
Mark

**Comment by kevzlou7979** [comment]
I would submit a PR for the new versions of GWT, TBroyer, new structure and optimizations , maven and other cool stuff,

**Comment by Legioth** [comment]
Hi. I'm not doing anything actively with this project at the moment, and I don't expect to come back to it in the future either.

If you are interested in continuing development, then it would probably be most practical if you would take over as a maintainer. The options would roughly be one of these:
1. I configure you as admin for this repository
2. You create a GitHub fork of this repo where you continue development, and I'll update the readme here to point to the fork.
3. I transfer ownership of this  repository to you.

**Comment by kevzlou7979** [comment]
Ok yeah that would be good , I will create a new repository for this and point me out. Thanks have a good day.

**Comment by kevzlou7979** [comment]
Here it is the new repo
https://github.com/kevzlou7979/Srp4Gwt
